### ISSUE TITLE
Question : Is it possible to redirect stdin/stdout to Shell Server?

### ISSUE THREAD

**Issue by HarelAshwal** [kstafford3/ssh2-shell-server#2]
LK"I

Hi ,

Thankyou for you excellent SSH2 server library!

Is it possible to use your library to redirect application stdin/stdout to ssh server session?
(for instance redirect the Bash shell to remotely control the PC. )

https://superuser.com/questions/1259194/redirect-process-stdin-and-stdout-to-ssh

Harel

**Comment by kstafford3** [comment]
Hi Harel,

The 'stream-initialized' event emitted by ShellSession provides you with a readable/writeable stream between the server and the client. 

From there, you're in a normal node environment. You could use something like node's [child_process.spawn](https://nodejs.org/docs/latest-v8.x/api/child_process.html#child_process_child_process_spawn_command_args_options
) to start a shell. Specifically check out the [options.stdio](https://nodejs.org/docs/latest-v8.x/api/child_process.html#child_process_options_stdio).
